# ------------------------------------------------------
# | ddddd   eeeee   ccccc   eeeee   bbbbb   u   u |
# | d   d   e       c       e       b    b  u   u |
# | d   d   eeee    c       eeee    bbbbb   u   u |
# | d   d   e       c       e       b    b  u   u |
# | ddddd   eeeee   ccccc   eeeee   bbbbb   uuuuu |
# ------------------------------------------------------
# HomeSmartHome – Docker-Stacks 
# File: docker-compose.yml
# Documentation: https://github.com/DaCeBu/docker-stacks
# Github Project: https://github.com/DaCeBu/docker-stacks.git
# Created by: DeCeBu (Data Excellence, Connectivity and Business)
# ------------------------------------------------------