version: '3.8'
services:
  mqtt:
    image: replace-with-correct-image
    container_name: mqtt
    restart: unless-stopped
    network_mode: "bridge"
    volumes:
      - ./config:/etc/mqtt
    environment:
      - TZ=Europe/Berlin
