# ------------------------------------------------------
# | ddddd   eeeee   ccccc   eeeee   bbbbb   u   u |
# | d   d   e       c       e       b    b  u   u |
# | d   d   eeee    c       eeee    bbbbb   u   u |
# | d   d   e       c       e       b    b  u   u |
# | ddddd   eeeee   ccccc   eeeee   bbbbb   uuuuu |
# ------------------------------------------------------
# HomeSmartHome – Docker-Stacks 
# File: stacks/influxdb/docker-compose.yml
# Documentation: https://github.com/DaCeBu/docker-stacks
# Github Project: https://github.com/DaCeBu/docker-stacks.git
# Created by: DeCeBu (Data Excellence, Connectivity and Business)
# ------------------------------------------------------

services:
  influxdb:
    image: influxdb:2.7.1
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"  # InfluxDB Web UI und API verfügbar auf Port 8086
    env_file:
      - ../../influxdb_secrets.env  # Pfad zur Datei mit den Umgebungsvariablen
    volumes:
      - influxdb-data:/var/lib/influxdb2  # Persistente Daten für InfluxDB
      - influxdb-conf:/etc/influxdb2  # Persistente Daten für InfluxDB
    networks:
      qnet-static-eth1:
        ipv4_address: 192.168.50.3  # Statische IP für InfluxDB

networks:
  qnet-static-eth1:
    name: qnap-static-eth1  # Das externe Netzwerk, das du bereits erstellt hast
    external: true

volumes:
  influxdb-data:
    driver: local  # Volumes für Daten und Persistenz
    driver_opts:
      type: none
      device: /share/CE_CACHEDEV1_DATA/Docker_DATA/volumes/influxdb_data
      o: bind

  influxdb-conf:
    driver: local  # Volumes für Daten und Persistenz
    driver_opts:
      type: none
      device: /share/CE_CACHEDEV1_DATA/Docker_DATA/volumes/influxdb_conf
      o: bind
