# ------------------------------------------------------
# | ddddd   eeeee   ccccc   eeeee   bbbbb   u   u |
# | d   d   e       c       e       b    b  u   u |
# | d   d   eeee    c       eeee    bbbbb   u   u |
# | d   d   e       c       e       b    b  u   u |
# | ddddd   eeeee   ccccc   eeeee   bbbbb   uuuuu |
# ------------------------------------------------------
# HomeSmartHome – Docker-Stacks 
# File: stacks/unbound/docker-compose.yml
# Documentation: https://github.com/DaCeBu/docker-stacks
# Github Project: https://github.com/DaCeBu/docker-stacks.git
# Created by: DeCeBu (Data Excellence, Connectivity and Business)
# ------------------------------------------------------

services:
  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    restart: unless-stopped
    networks:
      qnet-static-vlan70:
        ipv4_address: 192.168.70.6  # Statische IP für Unbound
    ports:
      - "53:53/tcp"  # DNS über TCP
      - "53:53/udp"  # DNS über UDP
    volumes:
      - unbound-data:/opt/unbound/etc/unbound  # Mount der benutzerdefinierten Konfiguration
    environment:
      - TZ=Europe/Berlin  # Zeitzone für den Container

networks:
  qnet-static-vlan70:
    name: qnet-static-vlan70  # Das externe Netzwerk, das du bereits erstellt hast
    external: true
  #unbound-network:
  #  driver: bridge

volumes:
  unbound-data:
    driver: local
    driver_opts:
      type: none
      device: /share/CE_CACHEDEV1_DATA/Docker_DATA/volumes/unbound_data
      o: bind
  
  redis-data:
    driver: local
    driver_opts:
      type: none
      device: /share/CE_CACHEDEV1_DATA/Docker_DATA/volumes/redis_data
      o: bind